version: '3.8'
services:
    # ...otros servicios (laravel.test, mysql)...

    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '\${WWWGROUP}'
        restart: unless-stopped
        networks:
            - sail
        volumes:
            - ./:/var/www/html
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
